package com.selenium.enus;

public enum ConfigProperties {

	URL,
	BROWSER,
	OVERRIDEREPORT,
	PASSEDTESTSCREENSHOT,
	FAILEDTESTSCREENSHOT,
	SKIPTESTSCREENSHOT,
	RETRYFAILEDTESTS,
	SENDRESULTOKIBANA,
	SELENIUMGRIDURL,
	ELASTICSEARCHDELETEURL,
	ELASTICSEARCHURL,
	RUNMODE;
}

//Underscore